spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1175640313043216
            client-secret: 46dea3606c1d8ec3c4aa76a97676e148
            redirect-uri:  https://2nv9g5sj6i.execute-api.ap-northeast-2.amazonaws.com/test/index/oauth2/code/facebook

            scope:
              - email
              - public_profile
          naver:
            client-id: UbTn1oyNc2ddhpxcUdKQ
            client-secret: eNlmSD77zq
            redirect-uri:  https://2nv9g5sj6i.execute-api.ap-northeast-2.amazonaws.com/test/index/oauth2/code/naver

            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
          google:
            client-id: 354098202531-cm8qe3s9g2jcjjg5naa3afdc4fv7fqh7.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://2nv9g5sj6i.execute-api.ap-northeast-2.amazonaws.com/test/index/oauth2/code/google
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #  datasource:
  #    hikari:
  #      username: sa
  #      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:postgresql://database-1.cczkxmegel3h.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: godol811
    password: Rhehf811!


jwt:
  secret_key: f-lab-reels
