spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1175640313043216
            client-secret: 46dea3606c1d8ec3c4aa76a97676e148
            redirect-uri:  "{baseUrl}/{action}/oauth2/code/{registrationId}"

            scope:
              - email
              - public_profile
          naver:
            client-id: UbTn1oyNc2ddhpxcUdKQ
            client-secret: eNlmSD77zq
            redirect-uri:  "{baseUrl}/{action}/oauth2/code/{registrationId}"

            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
          google:
            client-id: 354098202531-cm8qe3s9g2jcjjg5naa3afdc4fv7fqh7.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #  datasource:
  #    hikari:
  #      username: sa
  #      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://authdatabasestack-authinstance6c16cccd-oovzogtadgq3.cj8dzd5oyawf.ap-northeast-2.rds.amazonaws.com:3306
    username: admin
    password: qwer1234


jwt:
  secret_key: f-lab-reels
