spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${facebookClientId}
            client-secret: ${facebookSecret}
            redirect-uri:  "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - email
              - public_profile
          naver:
            client-id: ${naverClientId}
            client-secret: ${naverSecret}
            redirect-uri:  "{baseUrl}/{action}/oauth2/code/{registrationId}"

            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
          google:
            client-id: ${googleClientId}
            client-secret: ${googleSecret}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  #    datasource:
  #      hikari:
  #        username: sa
  #        jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
  #  h2:
  #    console:
  #      enabled: true

  datasource:
    url: ${databaseUrl}
    username: ${databaseUser}
    password: ${databasePassword}


jwt:
  secret_key: f-lab-reels
